<?php
session_start();

require_once __DIR__ . '/../config.php';
require_once ROOT_PATH . '/src/Database.php';
require_once ROOT_PATH . '/src/Router.php';
require_once ROOT_PATH . '/src/Auth.php';
require_once ROOT_PATH . '/src/helpers.php';
require_once ROOT_PATH . '/src/TextGenerator.php';
require_once ROOT_PATH . '/src/ILoveImgUpscaler.php';
require_once ROOT_PATH . '/src/Mailer.php';
require_once ROOT_PATH . '/src/Controllers/HomeController.php';
require_once ROOT_PATH . '/src/Controllers/ShopController.php';
require_once ROOT_PATH . '/src/Controllers/CartController.php';
require_once ROOT_PATH . '/src/Controllers/PaymentController.php';
require_once ROOT_PATH . '/src/Controllers/AdminController.php';

$router = new Router();

$router->get('/', [HomeController::class, 'index']);
$router->get('/boutique', [ShopController::class, 'index']);
$router->get('/tableau/{slug}', [ShopController::class, 'show']);
$router->get('/a-propos', [HomeController::class, 'about']);
$router->get('/contact', [HomeController::class, 'contact']);
$router->get('/cgv', [HomeController::class, 'cgv']);
$router->get('/mentions-legales', [HomeController::class, 'mentions']);
$router->get('/confidentialite', [HomeController::class, 'confidentialite']);
$router->get('/faq', [HomeController::class, 'faq']);
$router->get('/livraison', [HomeController::class, 'shipping']);
$router->get('/blog', [HomeController::class, 'blog']);
$router->get('/blog/categorie/{slug}', [HomeController::class, 'blogCategory']);
$router->get('/blog/{slug}', [HomeController::class, 'blogPost']);
$router->get('/sitemap.xml', function() { require PUBLIC_PATH . '/sitemap.xml.php'; });
$router->get('/suivi', [ShopController::class, 'trackingForm']);
$router->post('/suivi', [ShopController::class, 'trackingResult']);

$router->get('/panier', [CartController::class, 'index']);
$router->post('/panier/ajouter', [CartController::class, 'add']);
$router->post('/panier/supprimer', [CartController::class, 'remove']);
$router->get('/commande', [CartController::class, 'checkout']);
$router->post('/commande/valider', [PaymentController::class, 'process']);
$router->get('/commande/confirmation/{id}', [PaymentController::class, 'confirmation']);

$router->get('/api/relay-points', [PaymentController::class, 'relayPoints']);
$router->post('/api/paypal/create', [PaymentController::class, 'paypalCreateOrder']);
$router->post('/api/paypal/capture', [PaymentController::class, 'paypalCaptureOrder']);
$router->post('/api/paypal/cancel', [PaymentController::class, 'paypalCancelOrder']);
$router->post('/webhook/stripe', [PaymentController::class, 'stripeWebhook']);
$router->post('/webhook/paypal', [PaymentController::class, 'paypalWebhook']);

$router->get('/admin/login', [AdminController::class, 'loginForm']);
$router->post('/admin/login', [AdminController::class, 'login']);
$router->get('/admin/logout', [AdminController::class, 'logout']);
$router->get('/admin', [AdminController::class, 'dashboard']);
$router->get('/admin/tableaux', [AdminController::class, 'paintings']);
$router->get('/admin/tableaux/ajouter', [AdminController::class, 'addPaintingForm']);
$router->post('/admin/tableaux/ajouter', [AdminController::class, 'addPainting']);
$router->get('/admin/tableaux/modifier/{id}', [AdminController::class, 'editPaintingForm']);
$router->post('/admin/tableaux/modifier/{id}', [AdminController::class, 'editPainting']);
$router->post('/admin/tableaux/supprimer/{id}', [AdminController::class, 'deletePainting']);
$router->post('/admin/tableaux/{id}/photos', [AdminController::class, 'addPhotos']);
$router->post('/admin/tableaux/{id}/photo-supprimer/{photoId}', [AdminController::class, 'deletePhoto']);
$router->post('/admin/api/generate-description', [AdminController::class, 'generateDescription']);
$router->post('/admin/api/improve-text', [AdminController::class, 'improveText']);
$router->post('/admin/api/send-packlink', [AdminController::class, 'sendPacklink']);
$router->post('/admin/api/upscale-image', [AdminController::class, 'upscaleImage']);
$router->get('/admin/commandes', [AdminController::class, 'orders']);
$router->get('/admin/commandes/{id}', [AdminController::class, 'orderDetail']);
$router->post('/admin/commandes/{id}/statut', [AdminController::class, 'updateOrderStatus']);
$router->post('/admin/commandes/purger', [AdminController::class, 'purgeCancelledOrders']);
$router->get('/admin/parametres', [AdminController::class, 'settings']);
$router->post('/admin/parametres', [AdminController::class, 'saveSettings']);
$router->get('/admin/utilisateurs', [AdminController::class, 'users']);
$router->post('/admin/utilisateurs/ajouter', [AdminController::class, 'addUser']);
$router->post('/admin/utilisateurs/supprimer/{id}', [AdminController::class, 'deleteUser']);
$router->post('/admin/utilisateurs/password/{id}', [AdminController::class, 'changePassword']);
$router->get('/admin/faq', [AdminController::class, 'faqList']);
$router->post('/admin/faq/ajouter', [AdminController::class, 'addFaq']);
$router->post('/admin/faq/modifier/{id}', [AdminController::class, 'editFaq']);
$router->post('/admin/faq/supprimer/{id}', [AdminController::class, 'deleteFaq']);
$router->post('/admin/faq/reorder', [AdminController::class, 'reorderFaq']);
$router->get('/admin/promos', [AdminController::class, 'promoList']);
$router->post('/admin/promos/ajouter', [AdminController::class, 'addPromo']);
$router->post('/admin/promos/supprimer/{id}', [AdminController::class, 'deletePromo']);
$router->post('/admin/promos/toggle/{id}', [AdminController::class, 'togglePromo']);
$router->post('/api/promo/check', [CartController::class, 'checkPromo']);
$router->get('/admin/blog', [AdminController::class, 'blogList']);
$router->get('/admin/blog/ajouter', [AdminController::class, 'addBlogForm']);
$router->post('/admin/blog/ajouter', [AdminController::class, 'addBlog']);
$router->get('/admin/blog/modifier/{id}', [AdminController::class, 'editBlogForm']);
$router->post('/admin/blog/modifier/{id}', [AdminController::class, 'editBlog']);
$router->post('/admin/blog/supprimer/{id}', [AdminController::class, 'deleteBlog']);

$router->resolve();
