CREATE TABLE IF NOT EXISTS faq (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question VARCHAR(500) NOT NULL,
    answer TEXT NOT NULL,
    position INT NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO faq (question, answer, position, active) VALUES
('Qu''est-ce que la peinture au couteau ?', 'La peinture au couteau est une technique artistique qui consiste à appliquer la peinture directement sur la toile à l''aide d''un couteau à peindre (ou spatule) plutôt qu''avec un pinceau. Cette méthode permet de créer des textures riches et des empâtements généreux qui donnent du relief et du mouvement à l''œuvre. Chaque coup de couteau est unique, ce qui rend chaque tableau véritablement original.', 1, 1),
('Vos tableaux sont-ils des originaux ou des reproductions ?', 'Tous les tableaux proposés sur Vogel Art sont des œuvres originales, entièrement peintes à la main. Chaque toile est une pièce unique : il n''existe aucune copie ni reproduction. Vous recevrez un certificat d''authenticité signé par l''artiste avec votre achat.', 2, 1),
('Sur quel type de support peignez-vous ?', 'Je peins principalement sur des toiles en lin ou en coton de qualité professionnelle, montées sur châssis en bois. J''utilise de la peinture acrylique ou à l''huile de qualité artiste, garantissant une excellente tenue des couleurs dans le temps.', 3, 1),
('Comment entretenir et protéger mon tableau ?', 'Pour préserver votre tableau dans les meilleures conditions, évitez l''exposition directe au soleil et les environnements très humides. Dépoussiérez délicatement avec un chiffon doux et sec. Les tableaux peints à l''acrylique sont naturellement résistants. Pour les huiles, un vernis de protection est appliqué après séchage complet. N''utilisez jamais de produits chimiques ou d''eau pour le nettoyage.', 4, 1),
('Comment sont emballés et expédiés les tableaux ?', 'Chaque tableau est soigneusement emballé pour garantir une livraison en parfait état : protection des coins avec des renforts en carton, film à bulles sur l''ensemble de l''œuvre, puis mise en carton rigide adapté aux dimensions. Les envois sont assurés et un numéro de suivi vous est communiqué dès l''expédition.', 5, 1),
('Quels sont les délais de livraison ?', 'Les commandes sont généralement expédiées sous 3 à 5 jours ouvrés. Le délai de livraison varie ensuite selon le mode d''expédition choisi : 2 à 4 jours pour la France métropolitaine via Mondial Relay ou Colissimo. Pour les envois à l''étranger, comptez 5 à 10 jours ouvrés selon la destination.', 6, 1),
('Le paiement est-il sécurisé ?', 'Absolument. Nous proposons plusieurs moyens de paiement sécurisés : carte bancaire via Stripe (protocole SSL/TLS), PayPal, ou virement bancaire. Vos données de paiement ne sont jamais stockées sur notre site et sont traitées directement par nos partenaires certifiés.', 7, 1),
('Puis-je retourner ou échanger un tableau ?', 'Conformément à la législation française, vous disposez d''un délai de rétractation de 14 jours à compter de la réception de votre commande. Le tableau doit être retourné dans son emballage d''origine, en parfait état et non endommagé. Les frais de retour sont à la charge de l''acheteur. Le remboursement est effectué dans les 14 jours suivant la réception du retour.', 8, 1),
('Proposez-vous des commandes personnalisées ou sur-mesure ?', 'Oui, je réalise des commandes personnalisées selon vos souhaits : dimensions spécifiques, palette de couleurs adaptée à votre intérieur, sujet particulier, etc. N''hésitez pas à me contacter via la page Contact pour discuter de votre projet. Un devis vous sera proposé sans engagement.', 9, 1),
('Qui est l''artiste derrière Vogel Art ?', 'Vogel Art est le travail d''un artiste peintre passionné, spécialisé dans la peinture au couteau. Autodidacte et guidé par l''émotion, chaque toile reflète une sensibilité unique et un amour profond pour la couleur et la matière. Découvrez-en plus sur la page À propos.', 10, 1),
('Les couleurs du tableau seront-elles identiques à la photo ?', 'Les photographies sont réalisées avec le plus grand soin pour refléter au mieux les couleurs réelles de chaque œuvre. Cependant, de légères variations peuvent exister selon les réglages et la calibration de votre écran. La richesse des textures et des couleurs est toujours plus impressionnante en personne.', 11, 1),
('Livrez-vous en dehors de la France ?', 'Oui, nous livrons dans toute l''Union européenne. Les frais de port sont calculés en fonction de la destination et des dimensions du tableau. Pour les envois hors UE, contactez-nous pour obtenir un devis personnalisé incluant les éventuels frais de douane.', 12, 1);
